platform :ios, "7.0"

target "IOSLiiffee" do
  pod 'ReactiveCocoa', '~> 2.2.4'
  pod 'libextobjc'
  #pod 'RestKit' # conflicting with afnetworking version required for other pods
  pod 'InstagramKit', '2.1.0'
  pod 'Foursquare-API-v2', '1.4.4'
end 
